"""
RazorGuard AI - Investigation Agent

Converts ML fraud predictions and risk signals
into a structured investigation report.

The deterministic investigation always works.
Optional OpenAI reasoning is used only when
a valid API key and API credits are available.
"""

import os

from dotenv import load_dotenv
from openai import OpenAI


# ---------------------------------------------------------
# Environment
# ---------------------------------------------------------

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# Create OpenAI client only when an API key exists
client = None

if OPENAI_API_KEY:
    client = OpenAI(api_key=OPENAI_API_KEY)


# ---------------------------------------------------------
# OPTIONAL AI INVESTIGATION
# ---------------------------------------------------------

def ai_investigate(report):
    """
    Ask the LLM to investigate the transaction using
    ONLY the evidence generated by RazorGuard.

    If OpenAI is unavailable, return a safe fallback
    instead of crashing the application.
    """

    # -----------------------------------------------------
    # Check API availability
    # -----------------------------------------------------

    if client is None:

        return (
            "AI reasoning is currently unavailable because "
            "no OpenAI API key is configured.\n\n"
            "The deterministic RazorGuard risk engine was "
            "used instead."
        )

    # -----------------------------------------------------
    # Prepare evidence
    # -----------------------------------------------------

    strong_evidence = report.get("strong_signals", [])
    supporting_evidence = report.get("supporting_signals", [])

    evidence = f"""
Transaction ID: {report.get('transaction_id', 'UNKNOWN')}

Transaction Amount:
₹{report.get('transaction_amount', 0):,.2f}

Fraud Probability:
{report.get('fraud_probability', 0):.2f}%

Risk Score:
{report.get('risk_score', 0)}/100

Risk Level:
{report.get('risk_level', 'UNKNOWN')}

Primary Risk Evidence:
{chr(10).join("- " + str(s) for s in strong_evidence)
if strong_evidence else "- None"}

Supporting Risk Evidence:
{chr(10).join("- " + str(s) for s in supporting_evidence)
if supporting_evidence else "- None"}

Current Recommended Action:
{report.get('recommended_action', 'UNKNOWN')}
"""

    # -----------------------------------------------------
    # AI prompt
    # -----------------------------------------------------

    prompt = f"""
You are RazorGuard AI, a defensive payment-risk
investigation assistant.

Analyze the following transaction evidence.

IMPORTANT RULES:

1. Use ONLY the information provided below.
2. Do not invent customer information.
3. Do not claim the transaction is definitely fraudulent.
4. Explain which evidence contributes most to the risk.
5. Give a concise investigation conclusion.
6. Recommend an action consistent with the risk level.
7. This is a student prototype using synthetic/test data.
8. The system is defense-only and does not attempt to
   bypass payment security or perform unauthorized actions.

TRANSACTION EVIDENCE:

{evidence}

Return the investigation in this format:

RISK SUMMARY:
<2-3 sentences>

STRONGEST EVIDENCE:
<bullet points>

INVESTIGATION CONCLUSION:
<2-3 sentences>

RECOMMENDED ACTION:
<one action>

LIMITATION:
<one sentence>
"""

    # -----------------------------------------------------
    # Call OpenAI safely
    # -----------------------------------------------------

    try:

        response = client.responses.create(
            model="gpt-5.6-luna",
            input=prompt
        )

        return response.output_text

    except Exception as error:

        # Never allow an AI API failure to break
        # the RazorGuard application.

        print("\n[WARNING] OpenAI investigation unavailable.")
        print(f"[WARNING] {error}")

        return (
            "AI reasoning is currently unavailable. "
            "RazorGuard continued using its deterministic "
            "risk engine and evidence-based investigation."
        )


# ---------------------------------------------------------
# DETERMINISTIC INVESTIGATION REPORT
# ---------------------------------------------------------

def generate_investigation_report(
    transaction,
    fraud_probability,
    risk_score,
    risk_level,
    signals,
    recommended_action
):
    """
    Evidence-based investigation agent.

    It analyzes signals generated by the risk engine,
    prioritizes them, and produces a grounded report.
    """

    probability_percent = fraud_probability * 100

    # -----------------------------------------------------
    # 1. Determine confidence
    # -----------------------------------------------------

    if probability_percent >= 75:

        confidence = "High"

    elif probability_percent >= 50:

        confidence = "Moderate"

    else:

        confidence = "Low"

    # -----------------------------------------------------
    # 2. Classify risk signals
    # -----------------------------------------------------

    strong_signals = []
    supporting_signals = []

    strong_signal_types = {
        "EXTREME_AMOUNT_DEVIATION",
        "NEW_DEVICE",
        "MULTIPLE_FAILED_ATTEMPTS",
        "LOCATION_CHANGE"
    }

    for signal in signals:

        if isinstance(signal, dict):

            signal_type = signal.get("signal")
            message = signal.get("message", "")

            if signal_type in strong_signal_types:

                strong_signals.append(message)

            else:

                supporting_signals.append(message)

        else:

            supporting_signals.append(str(signal))

    # -----------------------------------------------------
    # 3. Generate primary concern
    # -----------------------------------------------------

    if strong_signals:

        primary_concern = (
            "Multiple strong risk indicators were detected, "
            "including "
            + "; ".join(strong_signals[:3])
            + "."
        )

    elif supporting_signals:

        primary_concern = (
            "The transaction shows several supporting risk "
            "indicators, including "
            + "; ".join(supporting_signals[:2])
            + "."
        )

    else:

        primary_concern = (
            "No significant behavioural risk indicators "
            "were detected."
        )

    # -----------------------------------------------------
    # 4. Generate overall assessment
    # -----------------------------------------------------

    if risk_level == "HIGH":

        assessment = (
            "The transaction presents a high level of risk "
            "based on the model prediction and multiple "
            "behavioural indicators. Strong customer "
            "verification is recommended before approval."
        )

    elif risk_level == "MEDIUM":

        assessment = (
            "The transaction presents elevated risk. "
            "The model prediction is supported by multiple "
            "behavioural indicators. Additional customer "
            "verification is recommended before approval."
        )

    else:

        assessment = (
            "The transaction appears relatively low risk "
            "based on the available model prediction and "
            "behavioural indicators."
        )

    # -----------------------------------------------------
    # 5. Create structured report
    # -----------------------------------------------------

    report = {

        "transaction_id":
            transaction.get("transaction_id", "UNKNOWN"),

        "transaction_amount":
            transaction.get("amount", 0),

        "fraud_probability":
            round(probability_percent, 2),

        "risk_score":
            risk_score,

        "risk_level":
            risk_level,

        "strong_signals":
            strong_signals,

        "supporting_signals":
            supporting_signals,

        "primary_concern":
            primary_concern,

        "assessment":
            assessment,

        "recommended_action":
            recommended_action,

        "confidence":
            confidence,

        "limitations":
            (
                "This investigation is based only on the "
                "available transaction features and model "
                "outputs. It does not constitute definitive "
                "proof of fraud."
            )
    }

    return report


# ---------------------------------------------------------
# PRINT DETERMINISTIC REPORT
# ---------------------------------------------------------

def print_investigation_report(report):
    """Display the RazorGuard investigation report."""

    print("\n")
    print("=" * 70)
    print("RAZORGUARD AI - AI INVESTIGATION REPORT")
    print("=" * 70)

    print(
        f"\nTransaction ID: "
        f"{report['transaction_id']}"
    )

    print(
        f"Transaction Amount: "
        f"₹{report['transaction_amount']:,.2f}"
    )

    print(
        f"\nFraud Probability: "
        f"{report['fraud_probability']:.2f}%"
    )

    print(
        f"Risk Score: "
        f"{report['risk_score']}/100"
    )

    print(
        f"Risk Level: "
        f"{report['risk_level']}"
    )

    # -----------------------------------------------------
    # Strong evidence
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("PRIMARY RISK EVIDENCE")
    print("-" * 70)

    if report["strong_signals"]:

        for index, signal in enumerate(
            report["strong_signals"],
            start=1
        ):

            print(f"{index}. {signal}")

    else:

        print("No primary risk evidence detected.")

    # -----------------------------------------------------
    # Supporting evidence
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("SUPPORTING RISK EVIDENCE")
    print("-" * 70)

    if report["supporting_signals"]:

        for index, signal in enumerate(
            report["supporting_signals"],
            start=1
        ):

            print(f"{index}. {signal}")

    else:

        print("No supporting risk evidence detected.")

    # -----------------------------------------------------
    # Primary concern
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("PRIMARY CONCERN")
    print("-" * 70)

    print(report["primary_concern"])

    # -----------------------------------------------------
    # Assessment
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("AI ASSESSMENT")
    print("-" * 70)

    print(report["assessment"])

    # -----------------------------------------------------
    # Recommendation
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("RECOMMENDED ACTION")
    print("-" * 70)

    print(report["recommended_action"])

    # -----------------------------------------------------
    # Confidence
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("CONFIDENCE")
    print("-" * 70)

    print(report["confidence"])

    # -----------------------------------------------------
    # Limitation
    # -----------------------------------------------------

    print("\n" + "-" * 70)
    print("LIMITATION")
    print("-" * 70)

    print(report["limitations"])

    print("\n" + "=" * 70)


# ---------------------------------------------------------
# PRINT OPTIONAL LLM INVESTIGATION
# ---------------------------------------------------------

def print_ai_investigation(ai_report):
    """Display the optional LLM investigation."""

    print("\n")
    print("=" * 70)
    print("RAZORGUARD AI - AI REASONING")
    print("=" * 70)

    print()
    print(ai_report)

    print("\n" + "=" * 70)